on:
    #Run workflows when a commit is pushed to main branch.
    push:
      branches:
        - "main"
    #Run workflows when pull request is created or updated.
    pull_request:
name: test
jobs:
    test:
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres:latest
          ports:
            - 5432:5432
          env:
            POSTGRES_DB: testdb
            POSTGRES_USER: testdb
            POSTGRES_PASSWORD: testpass
      steps:
      #Install and set up golang on runner
      - name: Set up golang
        uses: actions/setup-go@v5
        with:
            go-version: '>=1.20'
      #Check out my repository and download it to runner 
      #to run actions against my code.
      - name: Checkout
        uses: actions/checkout@v4
      - name: Database migration
        run: |
            go install github.com/sqldef/sqldef/cmd/psqldef@latest
            psqldef -U testdb -W testpass -h 127.0.0.1 -p 5432 testdb < ./_postgres/schema/table.sql
      #Generate test coverage
      - name: Run tests with coverage report output
        run: go test ./... -coverprofile=coverage.out
      #Report test coverage 
      - name: Report coverage
        uses: k1LoW/octocov-action@v1